### ISSUE TITLE
Do Website Review

### ISSUE THREAD

**Issue by tylerhcarter** [Team3128/team3128.github.io#6]
A couple people should go page by page through the entire website, and see what belongs, what needs to be improved, and what should get moved somewhere else.

Then, go through several other team websites and figuring out things that might be a good idea for us to add. FIRST Information/Robots/Awards/Handbook/etc?

**Comment by bobron** [comment]
So far, what we have is:

- [ ] About - FIRST
- [ ] About - Subteams
- [ ] About - Mentors and Leadership
- [ ] Outreach

**Comment by SentientBacon** [comment]
Website review kind of happened, with several key updates being ... updated. The about page on subteams is something that still needs to be tackled.
